# Generated by Django 4.1.7 on 2023-03-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order_id', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_route_name'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_stop_name'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_bus_name'),
        ),
    ]
